# Netlify config for manual deploy (drag & drop)

[build]
  publish = "dist"

# Default landing page
[[redirects]]
  from = "/"
  to = "/lander"
  status = 301

# SPA routing fix
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
